app:
  message: "Welcome Tenant 2!"
  featureX: true

# Example DB config (optional)
spring:
  datasource:
    url: jdbc:h2:mem:tenant2db
    username: sa
    password:
    driver-class-name: org.h2.Driver
