app:
  message: "Welcome Tenant 1!"
  featureX: true

# Example DB config (optional)
spring:
  datasource:
    url: jdbc:h2:mem:tenant1db
    username: sa
    password:
    driver-class-name: org.h2.Driver
